### ISSUE TITLE
[Link check fail] GPM-API

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2024#102]
https://registration.pps.eosdis.nasa.gov/registration/

is not reachable!

@ghiggi Is this intermittent? Maybe just link to some higher-level page.

**Comment by ghiggi** [comment]
Is 2 months that I can't connect and download via PPS. I sent mail but they don't answer ... I got account also deleted ...

**Comment by kmuehlbauer** [comment]
Ok then, please change that link to point to another resource.

**Comment by kmuehlbauer** [comment]
Seems like intermittent issue. We can reopen, if this comes back.
