### ISSUE TITLE
Invalid response 413 request entity too large

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2024#40]
Some things persist somehow.

When the notebook size exceeds a certain limit saving will generate an error, like this:

`Invalid response 413 request entity too large`

See also https://github.com/openradar/erad2022/issues/69.

A quick search connects this error to some problematic/missing configuration for nginx or whatever serve is used in the main jupyter docker container.

- https://discourse.jupyter.org/t/invalid-response-413-request-entity-too-large/13531
- https://github.com/jupyterlab/jupyterlab/issues/4214

Not sure, if we can do anything about it.

**Comment by kmuehlbauer** [comment]
@openradar/erad2024-team Is this still an issue?

**Comment by kmuehlbauer** [comment]
Obviously, yes:

![413_entity_too_large](https://github.com/user-attachments/assets/acaecb6b-4e39-441f-aeae-bddce9752316)

**Comment by kmuehlbauer** [comment]
XRef: https://discourse.jupyter.org/t/invalid-response-413-request-entity-too-large/13531/2

@mgrover1 Would be nice, if you could forward this to the pythia people. Thanks!

**Comment by mgrover1** [comment]
@kmuehlbauer - I am checking to see if we can set:

```bash
client_max_body_size 0
```

Which based on that thread, should resolve the issue.

**Comment by kmuehlbauer** [comment]
@mgrover1 That would have to be set on the pythia infrastructure AFAICT.

**Comment by ktyle** [comment]
@mgrover1 @kmuehlbauer I'm looking into it on our Pythia binder!

**Comment by kmuehlbauer** [comment]
@ktyle Thanks! If you fear to much load, you might experiment with increasing client_max_body_size. The issue happens when the notebook becomes to large due to huge images rendered therein.

**Comment by ktyle** [comment]
@zonca how might I configure my JS2 binderhub to configure the nginx ingress as above?

**Comment by zonca** [comment]
here is for jupyterhub:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1230

It should be the same or fairly similar in Binderhub:
https://binderhub.readthedocs.io/en/latest/https.html

**Comment by zonca** [comment]
so add:

        nginx.ingress.kubernetes.io/proxy-body-size: 64m

under `annotations` of your NGINX configuration in the binderhub yaml file

**Comment by ktyle** [comment]
Thanks, @zonca ! I have added that line to the configuration file and re-deployed. @kmuehlbauer @mgrover1 Can you give it another try and see if the 413 errors are no longer occurring? I just ran through the 2_BALTRAD_DRQC notebook and so far, no 413's.

**Comment by kmuehlbauer** [comment]
@ktyle @zonca Thanks for taking care :heart:! The changes resolved the issue :tada:!
