### ISSUE TITLE
New myst workflow does not run/render notebooks

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2024#50]
Unfortunately, the new workflow does not run the notebooks in CI, at least not in the nightly builds. 

From my perspective it would be better to have rendered output on the page. Otherwise viewers of the page would not see any output, forcing them to run them.

We now see that the new matplotlib 3.9.1 breaking Py-ART, see #49. Would be great to get a fix there in soon.

**Comment by mgrover1** [comment]
I can tackle this one 👍

**Comment by mgrover1** [comment]
Thank you so much @kmuehlbauer 👍

**Comment by kmuehlbauer** [comment]
Great to see the new Myst output on the page. Thanks @mgrover1 for making this possible.
