### ISSUE TITLE
Project: LROSE wind tools + PyDDA retrieval over complex terrain

### ISSUE THREAD

**Issue by jfigui** [openradar/erad2024#52]
Discussion of all topics related to the wind retrieval project

**Comment by jfigui** [comment]
@openradar/developers ,

I took the liberty to create this topic to discuss the wind retrieval exercise. I think we should start by identifying the main actors. Please add your name and contribution as a reply to this comment:
- @wolfidan , @jfigui : We will provide Pyrad config files that implement a PyDDA retrieval. (material post-course)

**Comment by kmuehlbauer** [comment]
@kmuehlbauer To showcase _complex terrain_, I could provide notebook (post-course?) for beamblockage calculation via DEM. Which dataset should I use for this?

**Comment by kmuehlbauer** [comment]
This also looks complete.
