### ISSUE TITLE
Project: Creating analysis-ready data with xradar with QVPs (xradar)

### ISSUE THREAD

**Issue by jfigui** [openradar/erad2024#53]
Discussion of all topics related to QVPs

**Comment by jfigui** [comment]
@openradar/erad2024-team , @wolfidan 

I took the liberty to open this issue to discuss the QVP exercise. Could we start by identifying the contributors to this project? Please add your name and contribution as a reply to this comment:
- @wolfidan , @jfigui : We will provide Pyrad config files to plot QVPs

**Comment by aladinor** [comment]
Thanks, Jordi, for creating this issue. I will work on analysis-ready data; one application could be QVPs or QPE. The idea is to show the advantages of having data in CFRadial2/FM301.

**Comment by aladinor** [comment]
By the way, @mgrover1 radar data has already been converted into ARCO format. How can I upload the data to the bucket?

**Comment by aladinor** [comment]
Analysis-ready data could be conditioned to this [issue](https://github.com/pydata/xarray/pull/9198) since we might need to pass credentials. Let me know your thoughts @kmuehlbauer @mgrover1

**Comment by mgrover1** [comment]
@aladinor - the zarr file is now available on the bucket!

```bash
https://js2.jetstream-cloud.org:8001/pythia/radar/erad2024/zarr_radar/erad_2024.zarr
```

**Comment by kmuehlbauer** [comment]
AFAICT this is up and running.
