### ISSUE TITLE
Project: Spaceborne / Ground Radar Comparison with GPM-API, xradar and wradlib

### ISSUE THREAD

**Issue by ghiggi** [openradar/erad2024#6]
I started to make a quick search of interesting rainy GPM overpass over Italy since 2019. 
We could select a couple of these events and ask for ground weather radar data from the Italian or Swiss network for analysis and comparison using xradar and wradlib.

All quicklooks can be downloaded [here](https://enacshare.epfl.ch/d6ukhase5iPNtmDXxYzdc).
Here below I showcase some interesting quicklooks (in terms of estimated near surface precipitation and reflectivity at Ku band)

![2019-10-07T04:13:47](https://github.com/openradar/erad2024/assets/19285200/2fb3433f-67b6-40e4-8654-4dfa2c075306)
![2019-10-07T04:13:47](https://github.com/openradar/erad2024/assets/19285200/3669e66d-29f4-484c-b367-5fe08b25c1c5)

![2020-06-04T21:00:31](https://github.com/openradar/erad2024/assets/19285200/6eb6b69a-8a50-48e8-97cd-ca5736e8225a)
![2020-06-04T21:00:31](https://github.com/openradar/erad2024/assets/19285200/69d2af24-f689-405e-9f98-49a0fd1b001a)

Genova  
![2019-10-15T02:00:41](https://github.com/openradar/erad2024/assets/19285200/72990083-8eeb-4377-be3c-50493c12f6a7)
![2019-10-15T02:00:41](https://github.com/openradar/erad2024/assets/19285200/a5ed5882-7ea7-462b-900c-85e15ce0fe8c)

![2022-06-28T16:45:39](https://github.com/openradar/erad2024/assets/19285200/68d9c1a5-377b-4357-8118-7e17294ae1e8)
![2022-06-28T16:45:39](https://github.com/openradar/erad2024/assets/19285200/e0bdd105-e678-46ab-8016-edea66758c5f)

Naples
![2019-11-17T07:18:41](https://github.com/openradar/erad2024/assets/19285200/158f05e6-90b2-491b-9ecf-36b2f9b1ab00)
![2019-11-17T07:18:41](https://github.com/openradar/erad2024/assets/19285200/bef88d0e-28e8-4cf5-99db-99f9f8ec0966)

Piemonte / Lake Maggiore (we could use MeteoSwiss data for these cases)
![2021-09-19T03:31:05](https://github.com/openradar/erad2024/assets/19285200/57ebc160-87a2-493c-b891-a767016dc59b)
![2021-09-19T03:31:05](https://github.com/openradar/erad2024/assets/19285200/f35e9c96-39ab-473e-9d7f-7afe9341e580)

![2022-08-18T02:10:47](https://github.com/openradar/erad2024/assets/19285200/03dccc27-4c00-409b-86c1-3dbdc2f6185d)
![2022-08-18T02:10:47](https://github.com/openradar/erad2024/assets/19285200/61435949-0f58-4b26-a4e1-bcf70f49c41f)

![2022-08-18T10:13:17](https://github.com/openradar/erad2024/assets/19285200/e05b92ef-76e0-4631-a833-d8c4db38f227)
![2022-08-18T10:13:17](https://github.com/openradar/erad2024/assets/19285200/f0a0a132-5111-44fb-9cdb-da4d08f32f1e)

**Comment by kmuehlbauer** [comment]
@ghiggi I'll add an example on Calibration of Ground Radar with GPM.

**Comment by ghiggi** [comment]
Hey @aladinor @kmuehlbauer. I started exploring what xradar currently offers to develop a notebook for ground-based radar PPI and RHI comparison with GPM ... and then dig a bit further with wradlib utilities.
I was thinking to develop tutorials using the Columbian Radar Network, NEXRAD and the Finnish network (via AWS). 
I might have some questions to address you on what are you planning to do in the coming weeks in terms of tutorials and what is in the roadmap in term of xradar accessor methods for `xr.Dataset` and `xr.Datatree` ... 

Can we maybe set up a meeting in the coming days?

**Comment by kmuehlbauer** [comment]
@ghiggi 

Yeah, going idea to coordinate. 

What I had in mind is something along this notebook from our lecture series (unrendered version, single PPI matching):

https://nbviewer.org/urls/git2.meteo.uni-bonn.de/projects/radarmeteorology/repository/revisions/SS2024/raw/notebooks/Lesson_07-Satellite_Calibration/Satellite_Calibration.ipynb.raw

I'd update the notebook to use gpm-api for loading. The matching is based on wradlib under the hood.

**Comment by aladinor** [comment]
Hi @kmuehlbauer and @ghiggi,

Thank you for bringing this up. I think we can use one of these examples to create a workflow using `xr.Datatree`. We could structure a datatree with all the radar/GPM data in our example and then export it to Zarr. I have a [poster](https://github.com/aladinor/raw2zarr/blob/main/notebooks/Poster.ipynb) for ERAD that demonstrates the advantages of using datatree.

Additionally, @mgrover1 mentioned that we can host the ARCO files on the Pythia S3 Object storage. This would ensure a smooth workflow during the short course.

Please let me know your thoughts.

**Comment by mgrover1** [comment]
Agreed - let's host the zarr store on Pythia + include both in this short course, as well as the Pythia cookbook.

Here is a link to an example of accessing data on the bucket!
https://projectpythia.org/lasso-those-clouds-cookbook/notebooks/LassoARMClouds.html#access-lasso-sgp-data-from-the-nsf-jetstream-cloud

Happy to help here!

**Comment by ghiggi** [comment]
Hi @kmuehlbauer ! 
I start to go through the notebook you mentioned but I coudn't find the `radarmeteorology.volume_matching` function in the repository. Could you provide it to me?

**Comment by kmuehlbauer** [comment]
@ghiggi I'm currently traveling and may not respond in due time.

AFAIK @vlouf's code is numpy based. It would be great to stay in the xarray world, if possible. 

The code you are missing is located in the same repository in the radarmeteorology subfolder:

https://git2.meteo.uni-bonn.de/projects/radarmeteorology/repository/revisions/SS2024/entry/radarmeteorology/radarmet.py

You might just copy over anything you need from there. I've planned to move this into wradlib later this year. Let me know how things go. :heart:

**Comment by ghiggi** [comment]
The documentation for the project are currently available on the GPM-API documentation at: 
- [Spaceborne-Ground Radar Matching (Methodology)](https://gpm-api.readthedocs.io/en/latest/tutorials/tutorial_03_SR_GR_Matching.html)
- [Spaceborne-Ground Radar Calibration (Application)](https://gpm-api.readthedocs.io/en/latest/tutorials/tutorial_03_SR_GR_Calibration.html)

We should discuss if we want to run the afternoon project on Binder (providing example GPM and xradar datasets) or rather let the students set up the environment on their laptop and analyze their own ground radar data of interest, with me providing the GPM overpass time required for the analysis.

**Comment by kmuehlbauer** [comment]
@ghiggi We should definitely have one example to run on binder. In general every participant will use it's own binder instance to run the notebooks. It would be great to merge this asap.

Regarding the Italian data, I've contacted Gianfranco Vulpiani to get some data for a recent overpass on 2024-05-21 06:30 UTC but did not hear back until now.

**Comment by aladinor** [comment]
Hi @ghiggi, 

Data from 8 Colombian radars are currently available in this Amazon s3 [bucket](https://registry.opendata.aws/ideam-radares/). It is open data but not FAIR data. If you can point me to some GPM overpasses I can get the data for you, or you can directly get it from there. 

Let me know your thoughts.

**Comment by ghiggi** [comment]
Yes I saw the data on S3 and I know how to retrieve it. If I find the time I will prepare the list of GPM overpass for ERAD. Otherwise we can assess the calibration after ERAD if you are interested ;)

**Comment by aladinor** [comment]
Totally interested. Let me know how can I help

**Comment by kmuehlbauer** [comment]
Great idea to follow up at or after ERAD, otherwise this seems very much complete.
