### ISSUE TITLE
Link with Zenodo, update DOI

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2024#78]
@openradar/erad2024-team I've taken the chance to link the repo with zenodo.

When we add a release here, this get's automagically uploaded to zenodo. When we've got that DOI, we can reinstate https://github.com/openradar/erad2024/blob/main/notebooks/how-to-cite.md.

**Comment by mgrover1** [comment]
Good to cut a release after we merge #106 and #107 ? I can handle the zenodo side 👍 @kmuehlbauer

**Comment by kmuehlbauer** [comment]
Yes, go for it.  🎉

**Comment by mgrover1** [comment]
this is resolved with the recent merged PRs
