### ISSUE TITLE
Remove duplicate environment.yml file in the repo

### ISSUE THREAD

**Issue by ghiggi** [openradar/erad2024#86]
I noticed that we have an updated `environment.yml` file in the `/binder` directory and one in the base directory. 
Should we maybe just keep the one in the `/binder` directory so stuffs must be not synchronized every time?

**Comment by kmuehlbauer** [comment]
@ghiggi `binder/environment.yml` is used to build the docker image and will finally be activated in the pythia hub. The one in the base directory was used before to build the book in GH Actions.

We've deactivated this as we wanted the books to be rendered and do this using the environment in the created docker image. So, yes the environment.yml in the base dir is not needed any more AFAICT.
