### ISSUE TITLE
coexistence of ARM and MeteoSwiss Py-ART

### ISSUE THREAD

**Issue by jfigui** [openradar/erad2024#92]

**Comment by jfigui** [comment]
@openradar/erad2024-team ,

We have an issue with the coexistence of the ARM and the MeteoSwiss versions of Py-ART. Some features that we use in our QPE exercise are in the MeteoSwiss version of Py-ART but not in the ARM version. We need your advise on how to proceed:
- Create two separate environments, one containing the MeteoSwiss version and one the ARM version
- Add the missing MeteoSwiss features to the ARM Py-ART
- Use the MeteoSwiss Py-ART instead of the ARM Py-ART in the course (all ARM features are available in the MeteoSwiss version)
- Other ...

Please let us know your preferred solution.

**Comment by kmuehlbauer** [comment]
@jfigui Maybe the quickest solution would be to add a second conda-environment. I've added it to todays meeting agenda for discussion.

**Comment by wolfidan** [comment]
@jfigui @kmuehlbauer 
One quick and dirty solution I used at last ERAD was to simply run 
pip install pyart_mch before running our part of the course.
I don't know if it's a viable solution but since our part would be in a parallel session it could maybe work.

**Comment by kmuehlbauer** [comment]
> One quick and dirty solution I used at last ERAD was to simply run
> pip install pyart_mch before running our part of the course.

Let's have this as our last resort. It's hacky and we should really try to come up with a proper solution for the course.

1. The cleanest solution would be to have the changes upstreamed to arm_pyart. 
2. Another option would be to create a second environment.
3. Hacky solution by overinstalling pyart_mch on-site.

If 1. is not manageable, we should aim for 2.

**Comment by mgrover1** [comment]
Can we put together an issue on the Py-ART side highlighting what is needed for 1:1 functionality for the short course? A list of modules/submodules?

**Comment by wolfidan** [comment]
Hi @mgrover1 ,
There are not so many features to add, I'm working on the PR at the moment, and making the unit tests for the features I added. Hopefully I can do the PR tomorrow.

**Comment by mgrover1** [comment]
wonderful! Please let me know how we can assist in getting this merged 👍

**Comment by mgrover1** [comment]
With the release of Py-ART 1.19.0, this should be resolved; let's wait for the conda-forge wheels to be released and try this :)

**Comment by kmuehlbauer** [comment]
Currently (#100) `pyrad_mch` and ``pyrad_arm` are installed into conda. Is this correct? If there is any possibility for clashes, one should be removed (pyrad_arm I suppose)?

**Comment by mgrover1** [comment]
Any issue with just using `pyrad_arm` @wolfidan @jfigui ? Now that those features are included in the latest release of ARM Py-ART

**Comment by wolfidan** [comment]
@mgrover1 , pyrad_arm is fine. I just forgot to remove pyrad_mch from the environment.yml. Sorry about this. Please see https://github.com/openradar/erad2024/pull/100

**Comment by kmuehlbauer** [comment]
Please reopen, if this isn't finished yet.

**Comment by wolfidan** [comment]
Hi @kmuehlbauer @mgrover1 
Just noticed that in the binder it is still the pyart version 1.18.7 that gets installed.
Could we please force 1.19, it would just be a matter of adapting environment.yml in the binder

**Comment by kmuehlbauer** [comment]
Wrong issue reported, just for reference. pyart 1.19 is still pending pr in conda-forge. Would be great, if this can be merged asap, @mgrover1 @zssherman. Thanks.

**Comment by mgrover1** [comment]
Merged 👍

**Comment by kmuehlbauer** [comment]
Great, let's wait another while an restart #104.
