### ISSUE TITLE
xarray v2024.7.1. version

### ISSUE THREAD

**Issue by aladinor** [openradar/erad2024#98]
Hi @kmuehlbauer and @mgrover1. As we already mentioned [here](https://github.com/openradar/erad2024/issues/94#issuecomment-2315335713), Analysis-Ready and GPM notebooks require xarray v2024.7.1... development version.  How can we include it in the docker/Pythia binder?

Ideally, we would like xarray from the GitHub repo. Something like 

```shell
python -m pip install git+https://github.com/pydata/xarray.git
```

Please let me know your thoughts.

**Comment by mgrover1** [comment]
@kmuehlbauer - do you know if there are plans for an xarray release soon?

**Comment by kmuehlbauer** [comment]
@aladinor This would have to be added in the appendix.txt in the binder folder.

**Comment by kmuehlbauer** [comment]
@mgrover1 No, I've missed this month's dev meetings. But there is no indication in the meeting notes. We can't depend on release which might not land in time. So best to add it to the docker image.

**Comment by mgrover1** [comment]
We can add that in the pip dependencies I believe?

**Comment by kmuehlbauer** [comment]
Let's try it like that, if that doesn't work, we can over install in appendix.txt.

**Comment by mgrover1** [comment]
@aladinor - just merged the PR, give it a shot when you get a chance 😄

**Comment by aladinor** [comment]
Great! Thanks @mgrover1
